//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2023 The KubeFin Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomAllocationConfiguration) DeepCopyInto(out *CustomAllocationConfiguration) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomAllocationConfiguration.
func (in *CustomAllocationConfiguration) DeepCopy() *CustomAllocationConfiguration {
	if in == nil {
		return nil
	}
	out := new(CustomAllocationConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CustomAllocationConfiguration) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomAllocationConfigurationList) DeepCopyInto(out *CustomAllocationConfigurationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CustomAllocationConfiguration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomAllocationConfigurationList.
func (in *CustomAllocationConfigurationList) DeepCopy() *CustomAllocationConfigurationList {
	if in == nil {
		return nil
	}
	out := new(CustomAllocationConfigurationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CustomAllocationConfigurationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomAllocationConfigurationSpec) DeepCopyInto(out *CustomAllocationConfigurationSpec) {
	*out = *in
	if in.WorkloadsAllocation != nil {
		in, out := &in.WorkloadsAllocation, &out.WorkloadsAllocation
		*out = make([]WorkloadAllocation, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomAllocationConfigurationSpec.
func (in *CustomAllocationConfigurationSpec) DeepCopy() *CustomAllocationConfigurationSpec {
	if in == nil {
		return nil
	}
	out := new(CustomAllocationConfigurationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodLabelSelectorExtract) DeepCopyInto(out *PodLabelSelectorExtract) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodLabelSelectorExtract.
func (in *PodLabelSelectorExtract) DeepCopy() *PodLabelSelectorExtract {
	if in == nil {
		return nil
	}
	out := new(PodLabelSelectorExtract)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadAllocation) DeepCopyInto(out *WorkloadAllocation) {
	*out = *in
	out.Target = in.Target
	out.PodLabelSelectorExtract = in.PodLabelSelectorExtract
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadAllocation.
func (in *WorkloadAllocation) DeepCopy() *WorkloadAllocation {
	if in == nil {
		return nil
	}
	out := new(WorkloadAllocation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadAllocationTarget) DeepCopyInto(out *WorkloadAllocationTarget) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadAllocationTarget.
func (in *WorkloadAllocationTarget) DeepCopy() *WorkloadAllocationTarget {
	if in == nil {
		return nil
	}
	out := new(WorkloadAllocationTarget)
	in.DeepCopyInto(out)
	return out
}
